version: '3'
services:
  timeapi:
    container_name: timeapi
    build:
      context: api
      dockerfile: Dockerfile.dev
    environment:
      DB_HOST: timedb
    env_file:
      - api/.env
    ports:
      - 127.0.0.1:9229:9229
    command:
      - run
      - run:dev
    volumes:
      - ./api/src:/usr/app/src
      - ./api/dist:/usr/app/dist
    depends_on:
      - timedb
  timeclient:
    container_name: timeclient
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      API_URL: "http://timeapi/api"
    ports:
      - 127.0.0.1:9228:9229
    command:
      - start
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
  timedb:
    container_name: timedb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - timedb:/data/db
  nginx-proxy:
    container_name: web-project-nginx
    image: nginx:mainline-alpine
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - timeapi
      - timeclient
  cas-stub:
    container_name: cas-stub
    image: registry.its.txstate.edu/cas-stub:base
    environment:
      NODE_ENV: development
    ports:
      - 2000:80
volumes:
  timedb: {}
